<a href="https://colab.research.google.com/github/amrahmani/ML/blob/main/Ch7_NeuronPerceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1:** Create a single-neuron **perceptron** with a sign activation function using PyTorch.

In [ ]:
import torch

# Define input features
inputs = torch.tensor([1.0, 2.0, 3.0])

# Define weights and bias
weights = torch.tensor([-0.5, -0.3, 0.1])
bias = torch.tensor(0.2)

# Define activation function (in this case, a sign function)
def activation(x):
    return 1 if x >= 0 else -1

# Calculate the weighted sum of inputs and add bias
weighted_sum = torch.sum(inputs * weights) + bias

# Apply activation function
output = activation(weighted_sum)

print("Output:", output)


Output: -1


**Problem 2:** Create a **Multilayer Perceptron (MLP)** with 2 input neurons, one hidden layer with 3 neurons, and one output neuron using PyTorch.

In [ ]:
# These lines import the necessary modules from the PyTorch library.
import torch
import torch.nn as nn

'''This block of code defines a class called MLP that represents our Multilayer Perceptron model.
It inherits from nn.Module, which is the base class for all neural network modules in PyTorch.
In Python, super() is a built-in function used to call methods of a superclass (or parent class) in a derived class (or subclass).
In the __init__ method, we define the layers of our MLP. nn.Linear represents a fully connected layer,
where the first parameter is the number of input neurons and the second parameter is the number of output neurons.
So, self.hidden represents the hidden layer with 2 input neurons and 3 output neurons,
and self.output represents the output layer with 3 input neurons and 1 output neuron.
We also initialize the ReLU activation function (nn.ReLU()) and store it in self.activation.
ReLU (Rectified Linear Unit) is a commonly used activation function in neural networks.'''

'''forward method defines the forward pass of our MLP. It takes an input tensor x and applies the layers sequentially.
x = self.activation(self.hidden(x)) performs a forward pass through the hidden layer (self.hidden) followed
 by the ReLU activation function (self.activation).
x = self.output(x) performs a forward pass through the output layer (self.output), which produces the final output of the model.
The output tensor x is returned as the result of the forward pass.'''
# Define the MLP class
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(2, 3)  # Hidden layer with 2 input neurons and 3 output neurons
        self.output = nn.Linear(3, 1)  # Output layer with 3 input neurons and 1 output neuron
        self.activation = nn.ReLU()    # ReLU activation function

    def forward(self, x):
        x = self.activation(self.hidden(x))  # Forward pass through the hidden layer with ReLU activation
        x = self.output(x)                   # Forward pass through the output layer
        return x

'''This line defines the input data for our MLP as a tensor. In this example, we have a single input data point with two features (2 inputs).'''
# Define input tensor
inputs = torch.tensor([[1.0, 2.0]])

# Create an instance of the MLP
mlp = MLP()

'''This line performs a forward pass through our MLP model (mlp) with the input data inputs. It calculates the output of the model based on the input data and the weights of the layers.
The result is stored in the variable output, '''
# Perform a forward pass
output = mlp(inputs)

print("Output:", output)


Output: tensor([[0.8499]], grad_fn=<AddmmBackward0>)


**Problem 3:** Create a **Multilayer Perceptron (MLP)** with 2 input neurons, 2 hidden layers (with 3 and 4 neurons respectively), and 2 output neurons using PyTorch.

In [3]:
import torch
import torch.nn as nn

# Define the MLP class
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden1 = nn.Linear(2, 3)  # First hidden layer with 2 input neurons and 3 output neurons
        self.hidden2 = nn.Linear(3, 4)  # Second hidden layer with 3 input neurons and 4 output neurons
        self.output = nn.Linear(4, 2)   # Output layer with 4 input neurons and 2 output neurons
        self.activation = nn.ReLU()     # ReLU activation function

    def forward(self, x):
        x = self.activation(self.hidden1(x))  # Forward pass through the first hidden layer with ReLU activation
        x = self.activation(self.hidden2(x))  # Forward pass through the second hidden layer with ReLU activation
        x = self.output(x)                    # Forward pass through the output layer
        return x

# Define input tensor
inputs = torch.tensor([[1.0, 2.0]])

# Create an instance of the MLP
mlp = MLP()

# Print weights
print("Weights of hidden layer 1:")
print(mlp.hidden1.weight)

print("Weights of hidden layer 2:")
print(mlp.hidden2.weight)

print("Weights of output layer:")
print(mlp.output.weight)
# print("Biases of output layer:")
# print(mlp.output.bias)

# Perform a forward pass
output = mlp(inputs)

print("Output:", output)


Weights of hidden layer 1:
Parameter containing:
tensor([[-0.2032,  0.3708],
        [-0.3923, -0.3055],
        [ 0.0887, -0.0536]], requires_grad=True)
Weights of hidden layer 2:
Parameter containing:
tensor([[ 0.2755, -0.0055, -0.2226],
        [-0.5205,  0.1980,  0.3620],
        [-0.5752,  0.4432,  0.3788],
        [-0.4613,  0.1508, -0.3776]], requires_grad=True)
Weights of output layer:
Parameter containing:
tensor([[-0.2955, -0.0441, -0.2471, -0.4003],
        [-0.0558, -0.2124, -0.2252, -0.4897]], requires_grad=True)
Output: tensor([[0.1836, 0.3899]], grad_fn=<AddmmBackward0>)


**Practice:**

**Task 1**: In problem 2, find common activation functions available in the PyTorch `torch.nn module`.

**Task 2**: In Problem 3, first apply identity activation functions for all layers, and then apply ReLU activation functions for all layers.

**Task 3:** In Problem 3, first apply `torch.nn.functional` for **the forward pass** with different activation functions (e.g., `torch.nn.functional.relu()`), then, apply the sign activation function using `torch.sign()`.

**Hint:** `torch.nn.functional` is ideal for quick and direct use of activation functions, especially when you don't need to create a custom module. `torch.nn` is more suitable for integrating activation functions into complex neural network architectures and building custom modules.